### ISSUE TITLE
fix error message on client delete for clients that have generated an authorization code

### ISSUE THREAD

**Issue by joestubbs** [tapis-project/authenticator#12]
Currently, clients that have generated at least one authorization code cannot be deleted due to an SQL constraint. I think we want this behavior (i.e., to not allow client delete after generating an authorization code) for auditability/tracability purposes, but we should have a better error message. We probably also need to allow users to deactivate the client (i.e., a "soft delete") to help with clean up.

**Comment by gcurbelo123** [comment]
This has been merged into dev
