### ISSUE TITLE
Consider defining "SK" before use in README

### ISSUE THREAD

**Issue by wesleyboar** [tapis-project/authenticator#35]
Consider defining the word "SK" in the README before using it.

<details><summary>Background</summary>

[In the README, the word SK is used without definition.](https://github.com/tapis-project/authenticator/tree/v1.3.4#start-the-server-locally) Searching ["sk abbreviation" in google](https://www.google.com/search?q=SK+abbreviation) gave me off-topic results*. I learned, by asking devs, that it means "security kernel". The first [search](https://www.google.com/search?q=security+kernel+%28sk%29) result I found—that actually has "security and "sk" in it—was TAPIS docs*, so I think it might not be widespread enough to use without explanation.

<sup>\* I understand my past Google searches may influence the results.</sup>

</details>

**Comment by joestubbs** [comment]
This is a good suggestion, thanks! I Have added something to the README. It is in the dev branch now but will make its way up as part of the 1.6.1 release.

**Comment by joestubbs** [comment]
Not sure when this got released but I did confirm it is in the latest version.
