### ISSUE TITLE
Why Is Logout Done via a Form?

### ISSUE THREAD

**Issue by wesleyboar** [tapis-project/authenticator#50]
## Overview

1. Why is the <del>login</del> <ins>logout</ins> field done via a form?
2. Can logout technically be an even that occurs upon visiting a URL?
    <sup>(So that after clicking a link or button, logout just happens.)</sup>
3. If it must be a form, may it change
	* from **[✓] Logout** and **[ Submit ]**
	* to just **[ Log out ]**?

**Comment by joestubbs** [comment]
I think question 1 should read "Why is the **logout** field done via a form?"
Assuming so, I don't see any reason to have a form at all -- I am open to removing it and making it be an event that occurs upon visiting the URL. Does that conform with how other sites do it?

**Comment by wesleyboar** [comment]
Yup, it should have said that. 🙂

<details><summary>That behavior conforms with how our Core Portal and Core CMS do it, and is common with many applications. <sub>(Click to toggle examples.)</sub></summary>

| portal | django cms | google |
| - | - | - |
| <img width="1200" alt="portal" src="https://github.com/tapis-project/authenticator/assets/62723358/c7d4f1ea-64ab-445a-b0fa-bed14ae185b0"> | <img width="1200" alt="django cms" src="https://github.com/tapis-project/authenticator/assets/62723358/336b882b-b70f-4c13-8822-7fd53affad62"> | <img width="1200" alt="google" src="https://github.com/tapis-project/authenticator/assets/62723358/f74b6122-7d56-4ede-a252-37acca734126"> |

</details>

**But**, I did test third-party websites, and found GitHub has a Logout confirmation form.

| github logout button | github logout confirmation |
| - | - |
| <img width="1200" alt="github" src="https://github.com/tapis-project/authenticator/assets/62723358/2ab0308b-c2f3-4d24-b416-bf6cdfe8b3c1"> | <img width="1200" alt="github logout form" src="https://github.com/tapis-project/authenticator/assets/62723358/b0995fab-26d9-40ce-b47f-347ef5255764"> |

Websites whose logout could have unintended consequences across other applications, like Tapis, may ask you to confirm logout. I think Tapis should retain it's logout form.

**Comment by wesleyboar** [comment]
Hm, but I think I am being told (in private chat) that logout on Tapis is just a simple logout of anyone using [tapis.io](http://tapis.io/) independently, and has no effect on client apps. If that's the case, C.J. and I would rather just not have the form. I'll report back what I learn.

**Comment by wesleyboar** [comment]
I want to propose logout form not exist, but I'm unsure of the "user experience flow" of doing so, because I don't know what steps a user takes to reach `/logout` endpoint, nor why.

So, for now, I'll just change the form **from** [✓] Logout and [ Submit ] **to** just [ Log out ] (and tweak messaging).

**Comment by wesleyboar** [comment]
Completed via #53.
